version: '3.8'

services:
  web:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped 